
package ted_lcss_gui;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import ted_lcss.LCSS;
import ted_lcss_d.LCSS_d;
import ted_lcss_googlemaps.TED_GoogleMaps;

/**
 *
 * @author Spiros Delviniotis , Konstantina Galouni
 */
public class JFrame extends javax.swing.JFrame {

    String file_1;
    String file_2;
    int flag_tab1 = 0;
    int flag_tab2 = 0;
    double result;
    private double lcss = 0;
    
    
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser_1 = new javax.swing.JFileChooser();
        dialog_error = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textarea_1 = new javax.swing.JTextField();
        button_choose_1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        textarea_2 = new javax.swing.JTextField();
        button_choose_2 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        textarea_3 = new javax.swing.JTextField();
        button_run_lcss_tab1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        textarea_result = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textarea_result_clock = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        textarea_4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        button_choose_3 = new javax.swing.JToggleButton();
        button_choose_4 = new javax.swing.JToggleButton();
        textarea_5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textarea_6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        button_run_lcss_tab2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        textarea_7 = new javax.swing.JTextField();
        textarea_result_tab2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textarea_result_clock_tab_2 = new javax.swing.JTextField();
        button_google_maps_tab2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        fileChooser_1.setDialogTitle("This is my open dialog");
        fileChooser_1.setFileFilter(new MyCustomFilter());

        dialog_error.setTitle("Error");
        dialog_error.setMinimumSize(new java.awt.Dimension(267, 190));
        dialog_error.setResizable(false);
        dialog_error.setType(java.awt.Window.Type.POPUP);

        jPanel3.setToolTipText("");

        jButton1.setText("Exit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Spiros Delviniotis\\Documents\\NetBeansProjects\\google_maps\\stop-icon.png")); // NOI18N
        jLabel4.setText("Wrong input data !");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addGap(22, 22, 22)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialog_errorLayout = new javax.swing.GroupLayout(dialog_error.getContentPane());
        dialog_error.getContentPane().setLayout(dialog_errorLayout);
        dialog_errorLayout.setHorizontalGroup(
            dialog_errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialog_errorLayout.setVerticalGroup(
            dialog_errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Files", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        jLabel1.setText("File 1 :");

        textarea_1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        textarea_1.setForeground(new java.awt.Color(153, 153, 153));
        textarea_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textarea_1.setText("insert a file");
        textarea_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textarea_1MouseClicked(evt);
            }
        });

        button_choose_1.setText("Choose...");
        button_choose_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_choose_1MouseClicked(evt);
            }
        });
        button_choose_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_choose_1ActionPerformed(evt);
            }
        });

        jLabel2.setText("File 2 :");

        textarea_2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        textarea_2.setForeground(new java.awt.Color(153, 153, 153));
        textarea_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textarea_2.setText("insert a file");
        textarea_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textarea_2MouseClicked(evt);
            }
        });

        button_choose_2.setText("Choose...");
        button_choose_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_choose_2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ε :");

        textarea_3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        textarea_3.setForeground(new java.awt.Color(153, 153, 153));
        textarea_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textarea_3.setText("insert double");
        textarea_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textarea_3MouseClicked(evt);
            }
        });

        button_run_lcss_tab1.setText("Run Lcss");
        button_run_lcss_tab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_run_lcss_tab1ActionPerformed(evt);
            }
        });

        jButton3.setText("Google maps");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textarea_3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(330, 330, 330)
                                .addComponent(jButton3)
                                .addGap(31, 31, 31)
                                .addComponent(button_run_lcss_tab1))
                            .addComponent(textarea_2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textarea_1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_choose_1)
                    .addComponent(button_choose_2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textarea_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(button_choose_1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textarea_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_choose_2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textarea_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_run_lcss_tab1)
                    .addComponent(jButton3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Output", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        jLabel5.setText("The similarity percentage is :");

        textarea_result.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textarea_result.setText("result");

        jLabel11.setText("Elapsed time:");

        textarea_result_clock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textarea_result_clock.setText("result");
        textarea_result_clock.setToolTipText("");
        textarea_result_clock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textarea_result_clockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textarea_result, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textarea_result_clock, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textarea_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(textarea_result_clock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel4);

        textarea_4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        textarea_4.setForeground(new java.awt.Color(153, 153, 153));
        textarea_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textarea_4.setText("insert a file");
        textarea_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textarea_4MouseClicked(evt);
            }
        });

        jLabel6.setText("File 1 :");

        button_choose_3.setText("Choose...");
        button_choose_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_choose_3MouseClicked(evt);
            }
        });
        button_choose_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_choose_3ActionPerformed(evt);
            }
        });

        button_choose_4.setText("Choose...");
        button_choose_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_choose_4ActionPerformed(evt);
            }
        });

        textarea_5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        textarea_5.setForeground(new java.awt.Color(153, 153, 153));
        textarea_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textarea_5.setText("insert a file");
        textarea_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textarea_5MouseClicked(evt);
            }
        });

        jLabel7.setText("File 2 :");

        textarea_6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        textarea_6.setForeground(new java.awt.Color(153, 153, 153));
        textarea_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textarea_6.setText("insert double");
        textarea_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textarea_6MouseClicked(evt);
            }
        });
        textarea_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textarea_6ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ε :");

        button_run_lcss_tab2.setText("Run Lcss");
        button_run_lcss_tab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_run_lcss_tab2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("δ :");

        textarea_7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        textarea_7.setForeground(new java.awt.Color(153, 153, 153));
        textarea_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textarea_7.setText("insert integer");
        textarea_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textarea_7MouseClicked(evt);
            }
        });
        textarea_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textarea_7ActionPerformed(evt);
            }
        });

        textarea_result_tab2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textarea_result_tab2.setText("result");

        jLabel12.setText("Best Match :");

        jLabel13.setText("Elapsed time :");

        textarea_result_clock_tab_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textarea_result_clock_tab_2.setText("result");

        button_google_maps_tab2.setText("Google maps");
        button_google_maps_tab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_google_maps_tab2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(textarea_6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textarea_7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(354, 354, 354)
                                        .addComponent(button_google_maps_tab2)
                                        .addGap(27, 27, 27)
                                        .addComponent(button_run_lcss_tab2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(textarea_4, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textarea_5, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_choose_3)
                    .addComponent(button_choose_4))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textarea_result_tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textarea_result_clock_tab_2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(button_choose_3)
                    .addComponent(textarea_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(button_choose_4)
                    .addComponent(textarea_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textarea_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(textarea_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_run_lcss_tab2)
                    .addComponent(button_google_maps_tab2))
                .addGap(106, 106, 106)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textarea_result_tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(textarea_result_clock_tab_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel5);

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        dialog_error.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        if (flag_tab1 == 0)
        {
            dialog_error.setVisible(true);
        }
        else
        {
            TED_GoogleMaps run = new TED_GoogleMaps();
            try {
                run.browser();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void button_run_lcss_tab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_run_lcss_tab1ActionPerformed
        // TODO add your handling code here:
        double input_e = 0;

        if ("insert double".equals(textarea_3.getText()) || "insert a file".equals(textarea_1.getText()) || "insert a file".equals(textarea_2.getText()))
        {
            dialog_error.setVisible(true);
        }
        else
        {
            input_e = Double.parseDouble(textarea_3.getText());
            file_1 = textarea_1.getText();
            file_2 = textarea_2.getText();
            
            textarea_result.setText("calculating...");
            textarea_result_clock.setText("calculating...");
            LCSS run = new LCSS(file_1,file_2,input_e);
            
            try {
                double lcss = 0;
                double min;
                
                /* run lcss */
                lcss = run.lcss();

                min = LCSS.line_counter_1;

                if (LCSS.line_counter_1 > LCSS.line_counter_2)
                {
                    min = LCSS.line_counter_2;
                }

                result = lcss/min;

                textarea_result.setText(String.valueOf(result*100) + " %");
                textarea_result_clock.setText(LCSS.clock.toString());
                
                flag_tab1 = 1;  //i will have coordinates_1,2
            } catch (IOException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_button_run_lcss_tab1ActionPerformed

    private void textarea_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textarea_3MouseClicked
        // TODO add your handling code here:
        textarea_3.setText("");
    }//GEN-LAST:event_textarea_3MouseClicked

    private void button_choose_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_choose_2ActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser_1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser_1.getSelectedFile();
            textarea_2.setText(file.getAbsolutePath());
        }
        else
        {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_button_choose_2ActionPerformed

    private void textarea_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textarea_2MouseClicked
        // TODO add your handling code here:
        textarea_2.setText("");
    }//GEN-LAST:event_textarea_2MouseClicked

    private void button_choose_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_choose_1ActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser_1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser_1.getSelectedFile();
            textarea_1.setText(file.getAbsolutePath());
        }
        else
        {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_button_choose_1ActionPerformed

    private void button_choose_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_choose_1MouseClicked
        // TODO add your handling code here:
        int returnVal = fileChooser_1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser_1.getSelectedFile();
            textarea_1.setText(file.getAbsolutePath());
        }
        else
        {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_button_choose_1MouseClicked

    private void textarea_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textarea_1MouseClicked
        // TODO add your handling code here:
        textarea_1.setText("");
    }//GEN-LAST:event_textarea_1MouseClicked

    private void textarea_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textarea_4MouseClicked
        // TODO add your handling code here:
        textarea_4.setText("");
    }//GEN-LAST:event_textarea_4MouseClicked

    private void button_choose_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_choose_3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_choose_3MouseClicked

    private void button_choose_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_choose_3ActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser_1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser_1.getSelectedFile();
            textarea_5.setText(file.getAbsolutePath());
        }
        else
        {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_button_choose_3ActionPerformed

    private void button_choose_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_choose_4ActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser_1.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser_1.getSelectedFile();
            textarea_4.setText(file.getAbsolutePath());
        }
        else
        {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_button_choose_4ActionPerformed

    private void textarea_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textarea_5MouseClicked
        // TODO add your handling code here:
        textarea_5.setText("");
    }//GEN-LAST:event_textarea_5MouseClicked

    private void textarea_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textarea_6MouseClicked
        // TODO add your handling code here:
        textarea_6.setText("");
    }//GEN-LAST:event_textarea_6MouseClicked

    private void button_run_lcss_tab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_run_lcss_tab2ActionPerformed
        // TODO add your handling code here:
        double input_e = 0;
        int input_d = 0;

        if ("insert double".equals(textarea_6.getText()) || "insert integer".equals(textarea_7.getText()) || "insert a file".equals(textarea_5.getText()) || "insert a file".equals(textarea_4.getText()))
        {
            dialog_error.setVisible(true);
        }
        else
        {
            input_e = Double.parseDouble(textarea_6.getText());
            input_d = Integer.parseInt(textarea_7.getText());

            file_1 = textarea_5.getText();
            file_2 = textarea_4.getText();
            
            /* run lcss */
            textarea_result_tab2.setText("calculating...");
            textarea_result_clock_tab_2.setText("calculating...");
            
            final LCSS_d run_1 = new LCSS_d();
            double min;

            try {
                lcss = run_1.lcss(file_1, file_2, input_e, input_d);
            } catch (IOException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            min = LCSS_d.line_counter_1;

            if (LCSS_d.line_counter_1 > LCSS_d.line_counter_2)
            {
                min = LCSS_d.line_counter_2;
            }

            result = lcss/min;

            textarea_result_tab2.setText(String.valueOf(result*100) + " %");
            textarea_result_clock_tab_2.setText(LCSS_d.clock_d.toString());
            
            flag_tab2 = 1;  //i will have coordinates_1,2
        }
        
    }//GEN-LAST:event_button_run_lcss_tab2ActionPerformed

    private void textarea_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textarea_7MouseClicked
        // TODO add your handling code here:
        textarea_7.setText("");
    }//GEN-LAST:event_textarea_7MouseClicked

    private void textarea_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textarea_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textarea_7ActionPerformed

    private void textarea_result_clockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textarea_result_clockActionPerformed
        // TODO add your handling code here:
        textarea_result_clock_tab_2.setText("");
    }//GEN-LAST:event_textarea_result_clockActionPerformed

    private void textarea_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textarea_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textarea_6ActionPerformed

    private void button_google_maps_tab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_google_maps_tab2ActionPerformed
        // TODO add your handling code here:
        
        if (flag_tab2 == 0)
        {
            dialog_error.setVisible(true);
        }
        else
        {
            TED_GoogleMaps run = new TED_GoogleMaps();
            try {
                run.browser();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_button_google_maps_tab2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton button_choose_1;
    private javax.swing.JToggleButton button_choose_2;
    private javax.swing.JToggleButton button_choose_3;
    private javax.swing.JToggleButton button_choose_4;
    private javax.swing.JButton button_google_maps_tab2;
    private javax.swing.JButton button_run_lcss_tab1;
    private javax.swing.JButton button_run_lcss_tab2;
    private javax.swing.JDialog dialog_error;
    private javax.swing.JFileChooser fileChooser_1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField textarea_1;
    private javax.swing.JTextField textarea_2;
    private javax.swing.JTextField textarea_3;
    private javax.swing.JTextField textarea_4;
    private javax.swing.JTextField textarea_5;
    private javax.swing.JTextField textarea_6;
    private javax.swing.JTextField textarea_7;
    private javax.swing.JTextField textarea_result;
    private javax.swing.JTextField textarea_result_clock;
    private javax.swing.JTextField textarea_result_clock_tab_2;
    private javax.swing.JTextField textarea_result_tab2;
    // End of variables declaration//GEN-END:variables
}
